name: pacman-actions
description: 'Installing pacman and its tools on Ubuntu24 environment github actions'
author: Termux Pacman
branding:
  icon: 'box'
  color: 'blue'
runs:
  using: 'node20'
  main: 'index.js'
